name: Release on main

on:
  push:
    branches:
      - main

jobs:
  Release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # GitVersion needs full history

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install GitVersion
        uses: GitTools/actions/gitversion/setup@v3
        with:
          versionSpec: '6.x'

      - name: Run GitVersion
        id: gitversion
        uses: GitTools/actions/gitversion/execute@v3
        with:
          disableCache: true

      - name: Display calculated version
        run: |
          echo "GitVersion calculated SemVer: ${{ steps.gitversion.outputs.semVer }}"

      - name: Restore dependencies
        run: dotnet restore src/GreeterCli.App/GreeterCli.App.csproj

      - name: Build
        run: dotnet build src/GreeterCli.App/GreeterCli.App.csproj --configuration Release --no-restore /p:Version=${{ steps.gitversion.outputs.semVer }}

      - name: Run tests
        run: dotnet test tests/GreeterCli.Tests/GreeterCli.Tests.csproj --no-build --logger "console"
      
      - name: Publish self-contained app for Windows
        run: dotnet publish src/GreeterCli.App/GreeterCli.App.csproj --configuration Release --runtime win-x64 --self-contained true --output ./publish/win /p:Version=${{ steps.gitversion.outputs.semVer }}

      - name: Publish self-contained app for Linux
        run: dotnet publish src/GreeterCli.App/GreeterCli.App.csproj --configuration Release --runtime linux-x64 --self-contained true --output ./publish/linux /p:Version=${{ steps.gitversion.outputs.semVer }}

      - name: Rename Windows output with version
        run: mv ./publish/win/GreeterCli.App.exe ./publish/Greeter-${{ steps.gitversion.outputs.semVer }}-win-x64.exe

      - name: Rename Linux output with version
        run: mv ./publish/linux/GreeterCli.App ./publish/Greeter-${{ steps.gitversion.outputs.semVer }}-linux-x64

      - name: Create and push tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag v${{ steps.gitversion.outputs.semVer }}
          git push origin v${{ steps.gitversion.outputs.semVer }}

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.gitversion.outputs.semVer }}
          files: |
            ./publish/Greeter-${{ steps.gitversion.outputs.semVer }}-win-x64.exe
            ./publish/Greeter-${{ steps.gitversion.outputs.semVer }}-linux-x64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}